name: Release
on:
  push:
    branches:
    - master
jobs:
  bundle:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.commit.outputs.hash }}
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
    - name: Bundle
      run: |
        deno --version
        mkdir bundle
        deno bundle mod.ts bundle/mod.ts
    - name: Commit
      id: commit
      run: |
        git config --local user.email "hello@tylerstewart.ca"
        git config --local user.name "Tyler Stewart"
        git add bundle
        git commit -m "publish"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
